name: CMake

on: [push]

jobs:
    build:
      runs-on: ubuntu-20.04

      strategy:
        matrix:
          build_type: ["Release", "Debug", "ALL_WARNINGS"]

      steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get install libeigen3-dev libhdf5-dev libboost-filesystem-dev libboost-dev libboost-graph-dev libyaml-cpp-dev libopenmpi-dev
          conda install -c conda-forge muq cmake spdlog
          ls $CONDA/lib/cmake
          ls $CONDA/lib/cmake/MUQ

      - name: Create Build Environment
        run: |
          cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_CXX_FLAGS_ALL_WARNINGS:STRING="-Wall -Wextra -Wpedantic -Werror" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_PREFIX_PATH=$CONDA/lib/cmake
          echo "done"

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          cmake --build .
